name: Deploy Blazor WebAssembly to Vercel

on:
  push:
    branches:
      - master # Specify the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Specify .NET 8

    - name: Build Blazor WebAssembly
      run: dotnet publish -c Release

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN  }}
      run: npx vercel deploy --prod --prebuilt --cwd=bin/Release/net8.0/wwwroot
